name: Databricks Bundle Deployment

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:

  deploy-dev:

    if: github.ref == 'refs/heads/dev'

    runs-on: ubuntu-latest

    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy DEV
        working-directory: bundles/jobs
        run: databricks bundle deploy -t dev
        env:
          DATABRICKS_HOST: ${{ secrets.DEV_DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DEV_DATABRICKS_TOKEN }}

  deploy-qa:

    if: github.ref == 'refs/heads/qa'

    runs-on: ubuntu-latest

    environment: qa

    steps:
      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy QA
        working-directory: bundles/jobs
        run: databricks bundle deploy -t qa
        env:
          DATABRICKS_HOST: ${{ secrets.QA_DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.QA_DATABRICKS_TOKEN }}

  deploy-prod:

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    environment: prod

    steps:
      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy PROD
        working-directory: bundles/jobs
        run: databricks bundle deploy -t prod
        env:
          DATABRICKS_HOST: ${{ secrets.PROD_DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}