name: Databricks 3 Environment CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy DEV
        working-directory: .bundles/jobs
        run: databricks bundle deploy -t dev
        env:
          DATABRICKS_HOST: ${{ secrets.DEV_DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DEV_DATABRICKS_TOKEN }}
  deploy-qa:
    needs: deploy-dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy QA
        working-directory: .bundles/jobs
        run: databricks bundle deploy -t qa
        env:
          DATABRICKS_HOST: ${{ secrets.QA_DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.QA_DATABRICKS_TOKEN }}
  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Deploy PROD
        working-directory: .bundles/jobs
        run: databricks bundle deploy -t prod
        env:
          DATABRICKS_HOST: ${{ secrets.PROD_DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.PROD_DATABRICKS_TOKEN }}